import { useNavigate } from "react-router";
import "../styles/Terms.scss";

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="terms">
      <header className="terms__header">
        <div className="terms__logo" onClick={() => navigate("/")}>
          <div className="logo-dot" />
          <span>HireSync</span>
        </div>
        <button className="terms__back" onClick={() => navigate("/")}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/></svg>
          Back to Home
        </button>
      </header>

      <main className="terms__content">
        <p className="eyebrow">LEGAL</p>
        <h1>Terms of Service</h1>
        <p className="terms__updated">Last updated: June 2026</p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By creating an account or using HireSync, you agree to be bound by these
            Terms of Service. If you do not agree, please do not use the platform.
          </p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>
            HireSync analyzes your resume or self-description along with a job
            description to generate an AI-powered interview prep plan, including
            questions, a match score, skill gap analysis, and a prep roadmap.
          </p>
        </section>

        <section>
          <h2>3. AI-Generated Content Disclaimer</h2>
          <p>
            Reports, questions, scores, and resumes generated by HireSync are produced
            by AI (Gemini) and are provided for guidance only. We do not guarantee
            interview outcomes, job offers, or the complete accuracy of any
            AI-generated content.
          </p>
        </section>

        <section>
          <h2>4. User Responsibilities</h2>
          <p>
            You agree to provide accurate information and to use HireSync only for
            lawful, personal career-preparation purposes. You may not upload content
            that infringes on others' rights or contains malicious code.
          </p>
        </section>

        <section>
          <h2>5. Account & Termination</h2>
          <p>
            We may suspend or terminate accounts that violate these terms or misuse
            the platform. You may delete your account at any time.
          </p>
        </section>

        <section>
          <h2>6. Limitation of Liability</h2>
          <p>
            HireSync is provided "as is." We are not liable for any damages arising
            from reliance on AI-generated interview prep content or resume outputs.
          </p>
        </section>

        <section>
          <h2>7. Contact Us</h2>
          <p>
            Questions about these terms? Email us at{" "}
            <a href="mailto:support.hiresync@gmail.com">support.hiresync@gmail.com</a>.
          </p>
        </section>
      </main>

      <footer className="terms__footer">
        <span>© 2026 HireSync. All rights reserved.</span>
      </footer>
    </div>
  );
};

export default Terms;